name: wolfram_tg
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies: 
  teledart: ^0.5.4

dev_dependencies:
  dart_code_metrics: ^5.6.0
  lints: ^2.0.0
