name: StephenWolframFellDown
version: '${project.version}'
main: com.foxfil.stephenwolframfelldown.Main
api-version: 1.19
authors: [ FoxFil ]
description: A plugin to make Stephen Wolfram fell down.
commands:
  summonstephen:
    description: Summon Stephen Wolfram!
  setlanguage:
    description: Set your plugin language!